from typing import Protocol, Sequence

from .models import CreateSchedule, Schedule


class I_ScheduleService(Protocol):
    def create_schedule(self, schedule: CreateSchedule) -> Schedule: ...
    def list_schedules(self) -> Sequence[Schedule]: ...
    def get_schedule_by_id(self, id_: str) -> Schedule: ...
    def find_schedules_by_date(self, date: str) -> Sequence[Schedule]: ...
    def update_schedule(self, schedule: Schedule) -> Schedule: ...
    def delete_schedule(self, id_: str) -> Schedule: ...
